


server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASSWORD:admin123}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}        # EC2 Public DNS hoặc Private IP
    prefer-ip-address: ${PREFER_IP:false}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin123}@${EUREKA_HOSTNAME}:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    renewal-percent-threshold: 0.85

# logging:
#   file:
#     name: logs/eureka-server.log
#   level:
#     root: INFO
#     com.netflix.discovery: INFO
#     org.springframework.cloud.netflix.eureka.server: INFO
